name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Deploy application to Azure VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: tejas2
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/tejas2/ai-devops-assignment
            git pull origin main
            docker-compose down
            docker-compose up -d --build
            docker ps